### ISSUE TITLE
PNG Images not loading

### ISSUE THREAD

**Issue by WenMoonTok** [Ge0rg3/StegOnline#59]
Several PNG images that I have tried to upload to view their bit planes at https://georgeom.net/StegOnline/upload are stuck loading. I have tried using different computers and different browsers to no avail.

 Help would be appreciated. Thank you.

**Comment by x011** [comment]
same here.

**Comment by Ge0rg3** [comment]
Thank you, there was a CSP issue due to site migration, this is now resolved

**Comment by WenMoonTok** [comment]
unfortunately the issue still exists, at least for large .png images.

**Comment by Ge0rg3** [comment]
Hey @WenMoonTok, please can you provide an example png? Many thanks!

**Comment by WenMoonTok** [comment]
@Ge0rg3 I sent it to you in a Twitter DM.
